### ISSUE TITLE
Link to rosetta code for quicksort in other languages?

### ISSUE THREAD

**Issue by moon-chilled** [kparc/kcc#12]
Near the end of the <a href="https://kcc.kparc.io/#how-to-solve-it">quicksort demonstration</a>, there are a couple of links to quicksort implementations in other languages, to compare.  These links go to assorted github gists.  Why not link to [rosetta code](http://rosettacode.org/wiki/Sorting_algorithms/Quicksort), whose purpose is to show the same algorithm in many different languages?

**Comment by kelas** [comment]
thanks for the suggestion, but that'd be an overkill.

as you must have noted, there are **no** hypertext links in narrative, even when relatively complex abstractions are mentioned which would normally warrant at least a wikipedia reference.

this is a deliberate design choice, because the last thing author wanted is to lose the reader, and it seemed to work for many.

as a matter of fact, in hindsight, a lot more could have been done in that respect. the next edition will be based on the lessons learned.

**Comment by moon-chilled** [comment]
ah, fair enough
